# Generated by Django 3.0.4 on 2020-03-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20200308_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='plus',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
