# Generated by Django 3.0.4 on 2020-03-10 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_plus_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Region')),
            ],
        ),
    ]
