# Generated by Django 3.0.4 on 2020-03-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_psn'),
    ]

    operations = [
        migrations.AddField(
            model_name='plus',
            name='period',
            field=models.CharField(choices=[('1', '1'), ('3', '3'), ('12', '12')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
