# Generated by Django 3.0.4 on 2020-03-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_plus_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psn',
            options={'verbose_name_plural': 'PSN'},
        ),
    ]
