# Generated by Django 3.0.4 on 2020-03-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_auto_20200311_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='psn',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
